; x2 数据生成器配置文件

[device]
; ── 基本几何参数 ──────────────────────────────────────────────
cell_type          = QLC          ; 本次生成的 CellType
wordline_count     = 768          ; WordLine 总数
page_count_in_block = 3048        ; 一个 Block 的总 Page 数
page_size          = 18432         ; 单个 Page 大小（字节）

; ══════════════════════════════════════════════════════════════
;  QLC（16 个状态）
; ══════════════════════════════════════════════════════════════
qlc_encoding = 15,7,6,4,12,8,0,2,3,1,5,13,9,11,10,14
qlc_region   = [6,377],[390,761]
qlc_mode = ratio
qlc_position_mode = none
qlc_parity_map = default
qlc_0  =1
qlc_1  =1
qlc_2  =1
qlc_3  =1
qlc_4  =1
qlc_5  =1
qlc_6  =1
qlc_7  =1
qlc_8  =1
qlc_9  =1
qlc_10 =1
qlc_11 =1
qlc_12 =1
qlc_13 =1
qlc_14 =1
qlc_15 =1

; ══════════════════════════════════════════════════════════════
; TLC（8 个状态）
; ══════════════════════════════════════════════════════════════
tlc_encoding = 7,6,4,0,2,3,1,5
tlc_region   = [0,5],[378,389],[762,767]
tlc_mode = ratio
tlc_position_mode = none
tlc_parity_map = default
tlc_0 = 1
tlc_1 = 1
tlc_2 = 1
tlc_3 = 1
tlc_4 = 1
tlc_5 = 1
tlc_6 = 1
tlc_7 = 1

[threading]
thread_count = 0

[logger]
level       = INFO
quiet       = false
thread_safe = true
color       = true

[output]
filename =
